# Generated by Django 5.0.7 on 2024-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('education_level', models.CharField(choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Vocational Training', 'Vocational Training'), ('Other', 'Other')], max_length=50)),
                ('other_education', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.BooleanField()),
                ('work_experience_details', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.BooleanField()),
                ('medical_conditions_details', models.TextField(blank=True, null=True)),
                ('training_program', models.CharField(choices=[('Advanced Cooking', 'Advanced Cooking'), ('Nutrition', 'Nutrition'), ('Childcare & Family Management', 'Childcare & Family Management'), ('Laundry', 'Laundry'), ('Cleaning', 'Cleaning'), ('Gardening', 'Gardening')], max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
